server:
    port: 8083
    servlet:
      context-path: /springDataDemo
spring:
  application:
    name: spring-data-demo


  datasource:
    url: jdbc:mysql://localhost:3306/green?useSSL=false
    username: root
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
